spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/movieplay
    username: root
    password: movieplay

  mail:
    username: 'official.movieplay@gmail.com'
    password: 'movieplay1234'

  redis:
    host: 'redis'
    port: 6379
    password:

jwt:
  secret: 'XUrYUhZfrEWLtykR7h80CrcITM59YLt5CRi3AdqZu33'