management:
  health:
    diskspace:
      enabled: true
    default:
      enabled: true
    db:
      enabled: true
  servlet:
    context-path: /manage
spa:
  default-file: /dist/index.html5
spring:
  web:
    resources:
      static-locations: classpath:/dist/
      add-mappings: "false"
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    username: sa
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test
  h2:
    console:
      path: /h2-console
      enabled: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  mvc:
    throw-exception-if-no-handler-found: true
  devtools:
    livereload:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${secret.mail.username}
    password: ${secret.mail.password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  redis:
    host: ${secret.redis.host}
    port: ${secret.redis.port}
    password: ${secret.redis.password}
logging:
  level:
    org:
      hibernate.SQL: DEBUG
      hibernate.type.descriptor.sql.BasicBinder: TRACE
      spring.boot: DEBUG
      spring.security: DEBUG
      spring.web: DEBUG
      apache.tiles: INFO
      spring.mail: DEBUG
    root: INFO
    com.samsung.security: DEBUG
server:
  error:
    include-stacktrace: never
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
    contextPath: /api
  address: 0.0.0.0
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
build:
  date: "@build.date@"
jwt:
  refresh-expired-in: '1296000000'  # Refresh Token 만료 시간 (15일)
  access-expired-in: '3600000' # Access Token 만료 시간 (1시간)
  cookieName: refreshToken
  secret: ${secret-jwt.secret}
springfox:
  documentation:
    swagger:
      use-model-v3: false
