secret:
  datasource:
    url: jdbc:mariadb://mariadb:3306/movieplay
    username: root
    password: movieplay

  mail:
    username: 'official.movieplay@gmail.com'
    password: 'dbql nngi acqx wryd'

  redis:
    host: localhost
    port: 6379
    password:

secret-jwt:
  secret: 'XUrYUhZfrEWLtykR7h80CrcITM59YLt5CRi3AdqZu33'